version: "3.6"

services:
  abuild:
    image: php-alpine:v${ALPINE_VERSION:-3.10}
    build: .
    volumes:
      - ./packages:/v${ALPINE_VERSION:-3.10}
      - ./distfiles:/var/cache/distfiles
      - apk-cache:/etc/apk/cache

volumes:
  apk-cache:

# vim:ts=2:sw=2:et
